In [11]:
import numpy as np

In [12]:
my_array = []
for i in range(1,100):
    if i % 5 == 0:
        my_array.append(i)


print(my_array)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [13]:
my_arr_10 = []
for a in my_array:
    if a % 10 == 0:
        my_arr_10.append(a)

print(my_arr_10)

[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [14]:
np.array(my_array)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [15]:
import random as r

my_random_list = [[r.randint(1,100) for i in range(2)] for _ in range(10)]

np.array(my_random_list)

array([[85, 24],
       [76, 87],
       [92, 98],
       [26, 62],
       [44, 87],
       [ 4, 80],
       [15, 21],
       [56, 70],
       [22, 59],
       [75, 21]])

In [16]:
original_array = [r.randint(5,100) for _ in range(10)]
my_second_array = []

for i in range(0, len(original_array)):
    if original_array[i] < original_array[i - 1]:
        my_second_array.append(original_array[i] - 5)
    else:
        my_second_array.append(original_array[i])

np.array(my_second_array)

array([93, 64, 58, 95,  2, 25, 42, 33, 41, 56])